// Generated by gencpp from file vehicle_msgs/WaypointsArray.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_WAYPOINTSARRAY_H
#define VEHICLE_MSGS_MESSAGE_WAYPOINTSARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vehicle_msgs/Waypoint.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct WaypointsArray_
{
  typedef WaypointsArray_<ContainerAllocator> Type;

  WaypointsArray_()
    : header()
    , waypoints()
    , preliminaryLoopClosure(false)
    , loopClosure(false)  {
    }
  WaypointsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoints(_alloc)
    , preliminaryLoopClosure(false)
    , loopClosure(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vehicle_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vehicle_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;

   typedef uint8_t _preliminaryLoopClosure_type;
  _preliminaryLoopClosure_type preliminaryLoopClosure;

   typedef uint8_t _loopClosure_type;
  _loopClosure_type loopClosure;





  typedef boost::shared_ptr< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointsArray_

typedef ::vehicle_msgs::WaypointsArray_<std::allocator<void> > WaypointsArray;

typedef boost::shared_ptr< ::vehicle_msgs::WaypointsArray > WaypointsArrayPtr;
typedef boost::shared_ptr< ::vehicle_msgs::WaypointsArray const> WaypointsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::WaypointsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::WaypointsArray_<ContainerAllocator1> & lhs, const ::vehicle_msgs::WaypointsArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypoints == rhs.waypoints &&
    lhs.preliminaryLoopClosure == rhs.preliminaryLoopClosure &&
    lhs.loopClosure == rhs.loopClosure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::WaypointsArray_<ContainerAllocator1> & lhs, const ::vehicle_msgs::WaypointsArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0473318081887a3740b7424ce44e5b16";
  }

  static const char* value(const ::vehicle_msgs::WaypointsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0473318081887a37ULL;
  static const uint64_t static_value2 = 0x40b7424ce44e5b16ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/WaypointsArray";
  }

  static const char* value(const ::vehicle_msgs::WaypointsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"vehicle_msgs/Waypoint[] waypoints\n"
"\n"
"bool preliminaryLoopClosure\n"
"bool loopClosure\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/Waypoint\n"
"float64 x\n"
"float64 y\n"
"\n"
"float64 id\n"
;
  }

  static const char* value(const ::vehicle_msgs::WaypointsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoints);
      stream.next(m.preliminaryLoopClosure);
      stream.next(m.loopClosure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::WaypointsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::WaypointsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vehicle_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "preliminaryLoopClosure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.preliminaryLoopClosure);
    s << indent << "loopClosure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loopClosure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_WAYPOINTSARRAY_H
