# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_msgs/Command.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Command(genpy.Message):
  _md5sum = "5f166b646303bdf36237e2c962a86181"
  _type = "vehicle_msgs/Command"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 theta_l
float64 theta_r
float64 torque_fl
float64 torque_fr
float64 torque_rl
float64 torque_rr"""
  __slots__ = ['theta_l','theta_r','torque_fl','torque_fr','torque_rl','torque_rr']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       theta_l,theta_r,torque_fl,torque_fr,torque_rl,torque_rr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Command, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.theta_l is None:
        self.theta_l = 0.
      if self.theta_r is None:
        self.theta_r = 0.
      if self.torque_fl is None:
        self.torque_fl = 0.
      if self.torque_fr is None:
        self.torque_fr = 0.
      if self.torque_rl is None:
        self.torque_rl = 0.
      if self.torque_rr is None:
        self.torque_rr = 0.
    else:
      self.theta_l = 0.
      self.theta_r = 0.
      self.torque_fl = 0.
      self.torque_fr = 0.
      self.torque_rl = 0.
      self.torque_rr = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.theta_l, _x.theta_r, _x.torque_fl, _x.torque_fr, _x.torque_rl, _x.torque_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.theta_l, _x.theta_r, _x.torque_fl, _x.torque_fr, _x.torque_rl, _x.torque_rr,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.theta_l, _x.theta_r, _x.torque_fl, _x.torque_fr, _x.torque_rl, _x.torque_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.theta_l, _x.theta_r, _x.torque_fl, _x.torque_fr, _x.torque_rl, _x.torque_rr,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
